import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), "utf8");
const retention = read("src/stores/useRetentionStore.ts");
assert.match(retention, /getStreakClaimKey\(loadedStartDayKey, 1, entry\)/, "旧 number[] 必须迁移为第一轮领取键");
assert.match(retention, /Math\.floor\(\(Math\.max\(1, streak\) - 1\) \/ 7\) \+ 1/, "轮次必须每7天循环");
assert.match(retention, /game-day-\$\{parseGameDayKey\(lastDayKey\) - streak \+ 1\}/, "连续周期必须使用游戏历法日序");
assert.match(retention, /winter: 3/, "游戏历法必须识别冬季，不能按公历月份解析");
assert.doesNotMatch(retention, /Date\.UTC|setUTCDate/, "连续周期不得用公历日期解析游戏季节键");
assert.doesNotMatch(retention, /streakClaimed\.value = \[\]/, "断签不得清空历史领取键");
const eventView = read("src/views/game/EventView.vue");
assert.match(eventView, /streakRound/); assert.match(eventView, /streakDayInRound/);
const pond = read("src/views/game/FishPondView.vue");
assert.match(pond, /findBreedByParents/); assert.match(pond, /未命中固定配方/);
assert.match(pond, /compendiumSpecies/); assert.match(pond, /selectedBreed\.parentBreedA/);
const cultivation = read("src/stores/useCultivationStore.ts");
assert.match(cultivation, /ice_soul_lotus: 10/); assert.match(cultivation, /purple_ganoderma: 12/);
assert.match(cultivation, /export const getSpiritCropAura/);
const farmActions = read("src/composables/useFarmActions.ts");
assert.equal((farmActions.match(/addAuraFromHarvest/g) ?? []).length, 3, "三条组合式收获路径应共用结算");
const farmView = read("src/views/game/FarmView.vue");
assert.equal((farmView.match(/addAuraFromHarvest/g) ?? []).length, 2, "页面两条兼容收获路径应共用结算");
const alchemy = read("src/views/game/AlchemyView.vue");
assert.match(alchemy, /useItemUsage/); assert.match(alchemy, /await itemUsage\.useItem\(pillId\)/);
assert.doesNotMatch(alchemy, /cultivation\.usePill/);
assert.match(alchemy, /usingPillId === recipe\.id/);
console.log("V3.3.18 专项静态测试通过");
